import { next } from '@vercel/functions';

// Same negative-lookahead as the SPA rewrite in vercel.json (api/, assets/,
// anything with a file extension never hits this) so their behavior stays
// completely untouched by this file.
export const config = {
  matcher: ['/((?!api/|assets/|.*\\.\\w+$).*)'],
};

// Must stay in sync with PATH_PAGE_MAP/DASHBOARD_TAB_PATHS/
// REPORTS_SUBTAB_PATHS/PURCHASES_SUBTAB_PATHS in src/App.jsx. Duplicated
// here (not imported) because this runs in an isolated Edge runtime that
// can't pull in App.jsx (a large JSX file, not a plain ESM module this
// runtime can load).
const KNOWN_PATHS = new Set([
  // Public marketing/auth pages
  '/', '/en', '/login', '/signup', '/forgot-password', '/terms', '/privacy',
  // Authenticated dashboard tabs (real URLs, but only actually usable once
  // logged in -- App.jsx's own onAuthStateChange redirects an anonymous
  // visitor here to /login rather than this middleware trying to read a
  // Supabase session cookie at the edge)
  '/home', '/pos', '/active-invoices', '/delivery-invoices', '/customers',
  '/inventory', '/purchases', '/promotions', '/reports', '/settings',
  // Reports/Purchases sub-tabs (their default sub-tab is served at the
  // bare /reports and /purchases paths above, not a separate path)
  '/reports/procurement', '/reports/expenses', '/reports/profit-loss', '/reports/vat',
  '/purchases/expenses',
]);

export default async function middleware(request) {
  const { pathname } = new URL(request.url);
  // /guides and /guides/<slug> are real static HTML files (public/guides/,
  // generated by scripts/build-guides.mjs) rewritten in via vercel.json --
  // not part of the SPA, so they're a prefix check rather than a
  // KNOWN_PATHS entry per slug.
  if (KNOWN_PATHS.has(pathname) || pathname === '/guides' || pathname.startsWith('/guides/')) return next();

  // Unknown path: serve the same SPA shell the normal rewrite would have,
  // but with a real 404 status instead of 200 -- src/App.jsx's own
  // pageForPath/currentPage logic renders the actual "not found" UI once
  // this loads client-side.
  const shell = await fetch(new URL('/index.html', request.url));
  const html = await shell.text();
  return new Response(html, { status: 404, headers: { 'content-type': 'text/html; charset=utf-8' } });
}
